title: Khin Soe
author: khinsoe3
email: ks2024639@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is Khin Soe's new site for knowledge-sharing.
theme: minima

# social links
twitter_username: KhinSoe19 # DO NOT include the @ character, or else the build will fail!
github_username:  khinsoe3 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

